apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: default
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Daemon       Off
        Log_Level    info
        Parsers_File parsers.conf

    [INPUT]
        Name              tail
        Tag               my-app.*
        Path              /var/log/*.log
        Parser            my-app
        DB                /var/container-state/flb_tail_my-app.db
        Mem_Buf_Limit     150MB
        Skip_Long_Lines   Off

    [FILTER]
        Name                lua
        Match               my-app.*
        Script              /fluent-bit/scripts/filter.lua
        Call                Process

    [OUTPUT]
        Name         gelf
        Match        *
        Host         192.168.1.2
        Port         12201
        Gelf_Short_Message_Key  log
        Gelf_Full_Message_Key   log
        Gelf_Timestamp_Key      time
        Gelf_Host_Key           host
        Gelf_Level_Key          level

  parsers.conf: |
    [PARSER]
        Name   my-app
        Format regex
        Regex  ^(?<time>[^ ]*)\s(?<stream>stdout|stderr)\s(?<log>.*)$

