version: "3.9"

networks:
  graylog:
    ipam:
      config:
        - subnet: 172.20.0.0/24

services:
  nginx:
    image: nginx:latest
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro/"
      - "./etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./etc/nginx/certs:/etc/nginx/certs"
      - "./etc/nginx/dhparam.pem:/etc/nginx/dhparam.pem"
    ports:
      - "80:80"
      - "443:443"
      - "9000:9000"        # Graylog web interface and REST API
      - "1514:1514"        # Syslog TCP
      - "1514:1514/udp"    # Syslog UDP
      - "12201:12201"      # GELF TCP
      - "12201:12201/udp"  # GELF UDP
    networks:
      graylog:
        ipv4_address: 172.20.0.11
    depends_on:
      - graylog1
      - graylog2
    restart: "always"

  mongodb1:
    image: "mongo:5.0"
    hostname: "mongodb1"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "mongodb-data-01:/data/db"
      - "./mongodb/initdb.d:/docker-entrypoint-initdb.d"
      - "./mongodb/init-replset.js:/init-replset.js"
    networks:
      graylog:
        ipv4_address: 172.20.0.2
    restart: "on-failure"

  mongodb2:
    image: "mongo:5.0"
    hostname: "mongodb2"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "mongodb-data-02:/data/db"
    networks:
      graylog:
        ipv4_address: 172.20.0.3
    restart: "on-failure"

  mongodb3:
    image: "mongo:5.0"
    hostname: "mongodb3"
    command: ["mongod", "--bind_ip_all", "--replSet", "rs0"]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "mongodb-data-03:/data/db"
    networks:
      graylog:
        ipv4_address: 172.20.0.4
    restart: "on-failure"

  elasticsearch1:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.2"
    container_name: "elasticsearch1"
    environment:
      - node.name=elasticsearch-node1
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "elasticsearch-data-01:/usr/share/elasticsearch/data"
    networks:
      graylog:
        ipv4_address: 172.20.0.5
#    ports:
#      - "9200:9200"
#      - "9300:9300"
    restart: "on-failure"

  elasticsearch2:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.15.2"
    container_name: "elasticsearch2"
    environment:
      - node.name=elasticsearch-node2
      - cluster.name=docker-cluster
      - discovery.seed_hosts=elasticsearch1,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch-node1,elasticsearch-node2
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "elasticsearch-data-02:/usr/share/elasticsearch/data"
    networks:
      graylog:
        ipv4_address: 172.20.0.6
#    ports:
#      - "9201:9200"
#      - "9301:9300"
    restart: "on-failure"

  graylog1:
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.2}"
    hostname: "graylog1"
    depends_on:
      - "mongodb1"
      - "mongodb2"
      - "mongodb3"
      - "elasticsearch1"
      - "elasticsearch2"
    entrypoint: "/docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb1:27017,mongodb2:27017,mongodb3:27017/graylog"
      GRAYLOG_ROOT_TIMEZONE: "America/Fortaleza"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch1:9200,http://elasticsearch2:9200"
#    ports:
#      - "9000:9000"        # Graylog web interface and REST API
#      - "1514:1514"        # Syslog TCP
#      - "1514:1514/udp"    # Syslog UDP
#      - "12201:12201"      # GELF TCP
#      - "12201:12201/udp"  # GELF UDP
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "graylog-data-01:/usr/share/graylog/data/data"
      - "graylog-journal-01:/usr/share/graylog/data/journal"
    networks:
      graylog:
        ipv4_address: 172.20.0.9
    restart: "on-failure"

  graylog2:
    image: "${GRAYLOG_IMAGE:-graylog/graylog:5.2}"
    hostname: "graylog2"
    depends_on:
      - "mongodb1"
      - "mongodb2"
      - "mongodb3"
      - "elasticsearch1"
      - "elasticsearch2"
    entrypoint: "/docker-entrypoint.sh"
    environment:
      GRAYLOG_IS_LEADER: "false"
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/data/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://127.0.0.1:9000/"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9001"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb1:27017,mongodb2:27017,mongodb3:27017/graylog"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch1:9200,http://elasticsearch2:9200"
      GRAYLOG_ROOT_TIMEZONE: "America/Fortaleza"
#    ports:
#      - "9001:9001"         # Graylog web interface and REST API
#      - "1515:1514"         # Syslog TCP
#      - "1515:1514/udp"     # Syslog UDP
#      - "12202:12201"       # GELF TCP
#      - "12202:12201/udp"   # GELF UDP
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "graylog-data-02:/usr/share/graylog/data/data"
      - "graylog-journal-02:/usr/share/graylog/data/journal"
    networks:
      graylog:
        ipv4_address: 172.20.0.10
    restart: "on-failure"

volumes:
  graylog-data-01:
  graylog-data-02:
  graylog-journal-01:
  graylog-journal-02:
  mongodb-data-01:
  mongodb-data-02:
  mongodb-data-03:
  elasticsearch-data-01:
  elasticsearch-data-02:

